'use client'
import 'bootstrap/dist/css/bootstrap.min.css'
import type { Metadata } from 'next'
import { Inter, Roboto, Poppins } from 'next/font/google'
import './globals.css'
import { AppHeader } from '@/components/header/app.header'
import AppFooter from '@/components/footer/app.footer'
import { ContextProvider } from "@/context/Context"
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Đồ án tốt nghiệp',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //  const [display, setDisplay] = React.useState<boolean>(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <AppHeader />
          <div className='container'>
            {children}
          </div>
          <AppFooter />
          <ToastContainer />
        </ContextProvider>
      </body>
    </html>
  )
}
